-- MySQL Script generated by MySQL Workbench
-- Wed Sep  4 04:25:24 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ilhasql
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ilhasql
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ilhasql` DEFAULT CHARACTER SET latin1 ;
USE `ilhasql` ;

-- -----------------------------------------------------
-- Table `ilhasql`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ilhasql`.`cidade` (
  nome_cidade VARCHAR(255) NOT NULL,
  guilda VARCHAR(45) NULL DEFAULT NULL,
  guildmaster VARCHAR(45) NULL DEFAULT NULL,
  quantidade_habitantes INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (nome_cidade))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ilhasql`.`aventureiro`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `ilhasql`.`aventureiro`(
 cartao_aventureiro VARCHAR(255) NOT NULL,
 nome varchar(45) NULL DEFAULT NULL,
 ranque int(2) NULL DEFAULT NULL,
 classe varchar(45) NULL DEFAULT NULL,
 gold int(11) null default null,
 nome_cidade varchar(255) null default null,
 primary key (cartao_aventureiro),
 foreign key aventureiro(nome_cidade) REFERENCES cidade(nome_cidade)
);

CREATE TABLE IF NOT EXISTS `ilhasql`.`Comidas`(
	nome VARCHAR(255) NOT NULL,
    preco int(11) null default null,
    validade int(11) null default null
);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO cidade (nome_cidade,guilda, guildmaster, quantidade_Habitantes) VALUES ("Cidade SQL", "Guilda SQL", "Mestre SQL", 21659);
INSERT INTO cidade (nome_cidade,guilda, guildmaster, quantidade_Habitantes) VALUES ("Cidade dos Mercadores","Guilda de Mercadores","Mestre Stonkes",8896);
INSERT INTO cidade (nome_cidade,guilda, guildmaster, quantidade_Habitantes) VALUES ("Cidade dos Magos","Guilda dos Magos","Mestre dos Magos",12564);

INSERT INTO Comidas(nome, preco, validade) VALUES ("Carne de Vaca",20,3);
INSERT INTO Comidas(nome, preco, validade) VALUES ("Carne de Porco",15,2);
INSERT INTO Comidas(nome, preco, validade) VALUES ("Repolho",5,6);
INSERT INTO Comidas(nome, preco, validade) VALUES ("Cenoura",6,7);
